name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -tags="gl" -o GoYoung.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GoYoung
        path: GoYoung.exe
